
            [theme]
            base="light"
            primaryColor="#d33682"
            backgroundColor="#f0f2f6"
            secondaryBackgroundColor="#ffffff"
            textColor="#000000"
            